### ISSUE TITLE
Low framerate 3d models

### ISSUE THREAD

**Issue by IronPiston** [Fuzss/consolehud#7] opened 2019-07-13 20:51 UTC
The models for the paper doll and rotating chest icon for saving appear to be running at a noticeably lower framerate than the game normally does. Parts of the paper doll appear to move smoothly, like it rotating, but arm and leg movement are choppy. For reference, my client is at a locked 60fps.

**Comment by Fuzss** [comment] 2019-07-14 10:25
Wow, well spotted.

For the chest icon, it's not a 3d model, just an animated texture. Therefor it's restricted by the amount of frames it's given. If it really bothers you you can disable the "Rotating Model" option in the config.

For the paper doll I already tried to make it run at more than 20 fps, but for some reason the model then starts to stutter a lot. Will have to look into this again, but it's not a priority.

**Comment by Fuzss** [comment] 2019-10-06 21:31
Found the cause, fix will be released in the next version after v1.4.3.

**Closed as completed by Fuzss** 2019-10-06 21:31 UTC
