### ISSUE TITLE
paper doll jittering

### ISSUE THREAD

**Issue by geniiii** [Fuzss/consolehud#2] opened 2019-05-11 12:07 UTC
there's a (very noticeable) "jitter" when moving around the paper doll

**Comment by Fuzss** [comment] 2019-05-12 11:22
I'll look into it when I find the time. Thanks for the report.

**Comment by Fuzss** [comment] 2019-06-04 10:53
Found the cause for this issue. It'll be fixed in the next major update (v1.3).

**Closed as completed by Fuzss** 2019-06-04 10:53 UTC
