### ISSUE TITLE
Menu Notes say "missino"

### ISSUE THREAD

**Issue by Camawama** [Fuzss/consolehud#34] opened 2021-01-07 06:21 UTC
The Menu Tips say "missino" everytime.

**Comment by Fuzss** [comment] 2021-01-07 07:13
Duplicate of #33

**Closed as completed by Fuzss** 2021-01-07 07:13 UTC

**Comment by Fuzss** [comment] 2021-01-08 12:03
Can you please test if [this](https://mega.nz/file/HM0lXawR#WU-FuHvP5aJngq91nRK8hsUzBbjmYxC9WHAGVyYv_30) build fixes the issue?

**Comment by Fuzss** [comment] 2021-01-08 12:35
Or [this](https://mega.nz/file/nJkCTYCR#a2CdVDvEMMqE2NQaWYMaINXOUKJICsJUiUO4DloYLf4). Please also send me the `latest.log` file.
