### ISSUE TITLE
Fix: fires are green in paperdoll

### ISSUE THREAD

**Issue by sepsol** [Fuzss/consolehud#16] opened 2019-10-16 10:09 UTC
![image](https://user-images.githubusercontent.com/47871887/66909785-39bcc800-f01a-11e9-9839-b978d966d575.png)

**Comment by Fuzss** [comment] 2019-10-25 18:48
Please provide more information, like everything you're using here basically, meaning mods, resource packs, shader pack, Forge version. So far I've been unable to reproduce the issue.

**Comment by sepsol** [comment] 2019-10-25 20:09
It was because of shaders. It was SEUS Renewed 1.0.0
Minecraft 1.14.4
Forge 28.1.0
It even rendered the fires on the paperdoll inside inventory as green.
I'm now using BSL shaders and it's fine.

Please do something about #15 - That is really annoying. I can provide more info and screen recordings of the issue if you'd like.

**Comment by Fuzss** [comment] 2019-10-25 20:35
Thanks, in this case there isn't really anything I can do about it though.

For the frame rate issue mentioned in #15, that has already been fixed in e5ef872. The resolution issue I've been unable to verify so far.
I'm currently unable to work on and therefor finish the next update of this mod though, so no idea when it'll be released.

**Closed as completed** 2019-10-26 13:19 UTC
