### ISSUE TITLE
NPE with More Player Models Mod

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/consolehud#1] opened 2018-08-06 01:00 UTC
Forge v14.23.4.2745-1.12.2
More Player Models v18jan18
Console Hud v1.1.1

I get the following NPE spammed in the log while in my world when the More Player Models mod is installed.

`java.lang.NullPointerException: null
	at noppes.mpm.client.layer.LayerBackItem.render(LayerBackItem.java:38) ~[LayerBackItem.class:?]
	at noppes.mpm.client.layer.LayerInterface.doRenderLayer(LayerInterface.java:71) ~[LayerInterface.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.renderLayers(RenderLivingBase.java:557) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.doRender(RenderLivingBase.java:270) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:71) [cct.class:?]
	at net.minecraft.client.renderer.entity.RenderSubPlayer.doRender(RenderSubPlayer.java:80) [RenderSubPlayer.class:?]
	at net.minecraft.client.renderer.entity.RenderSubPlayer.doRender(RenderSubPlayer.java:18) [RenderSubPlayer.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:416) [bzf.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.drawEntityOnScreen(SourceFile:128) [bmx.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.drawGuiContainerBackgroundLayer(SourceFile:94) [bmx.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75) [bmg.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:51) [bmr.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.drawScreen(SourceFile:75) [bmx.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at Reflector.callVoid(Reflector.java:648) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3940) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by Fuzss** [comment] 2019-04-11 17:57
Sorry I haven't gotten back to you in such a long time.

After playing around a little with the More Player Models mod I wasn't able to reproduce your issue. From the look of things the NPE also seems to be caused by More Player Models and not my mod.

I'll close this issue now, since it has been such a long time, but if you still have this problem and are able to reproduce it you're more than welcome to open a new issue where we can investigate.

**Closed as completed by Fuzss** 2019-04-11 17:57 UTC
