### ISSUE TITLE
The game crashes and exits when dying in a world

### ISSUE THREAD

**Issue by sepsol** [Fuzss/consolehud#18] opened 2019-10-31 12:05 UTC
I don't understand crash reports but from the latest.log I suspected that it might be from Console Experience. If not, please guide me in the right direction to report this issue to the respective developers of the troubling mod. Here are some useful files:

[crash-2019-10-31_12.19.30-client.txt](https://gist.github.com/SepSol/b0a2785ed951fb7b285456fd39b1844c)
[diagnostic.log](https://gist.github.com/SepSol/d2bb8e33ecc4401642f5fdb71a0d9066)
[debug.log](https://gist.github.com/SepSol/ff2172de8aa52011eb66629b60130a26)
[latest.log](https://gist.github.com/SepSol/407232e878c49bfefdaab81cb2833132)

**My specs:**
- Minecraft 1.14.4
- Forge 28.1.70
- OptiFine HD U F4
- ConsoleExperience-v1.5b3-1.14.4

**Steps to reproduce:**
1. open the game
2. create a new world
3. die
4. game crashes with exit code of -1 (0xffffffff) before allowing you to choose 'respawn'
5. now launch the game again and select 'respawn' to continue playing

**Comment by Fuzss** [comment] 2019-10-31 22:44
The crash report is all I need, thank you. Unfortunately the crash is caused by the Fashion mod. It seems to be unable to handle a dead player being rendered...

I can't provide a proper fix as this has to happen in Fashion itself, but there is a workaround by simply disabling the paper doll whenever the player is dead. 

Here is a special version of Console Experience so you can continue playing with both mods installed as it might be a while before I have the next beta including this workaround ready to upload on Curse.
https://mega.nz/#!SIdBka6T!ZN30SS0Y73Ntlw24lBk5fFKFubXlMwNGa-kbp6HlBzM

**Comment by Fuzss** [comment] 2019-10-31 22:45
Closing this as it's not an issue caused by Console Experience.

**Closed as completed by Fuzss** 2019-10-31 22:45 UTC

**Comment by sepsol** [comment] 2019-10-31 23:00
That worked really well! Thank you so much! :)
